# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "638b227010452168039193ed92215dfb"
name = "ui-ext-hosted-jam"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[metaobjects.app.faq]
name = "FAQ"

[metaobjects.app.faq.fields.question]
name = "Question"
type = "single_line_text_field"
required = true

[metaobjects.app.faq.fields.answer]
name = "Answer"
type = "multi_line_text_field"
required = true

[metaobjects.app.faq.fields.show_on_faq_page]
name = "Show on FAQ page"
type = "boolean"

[sidekick]
extensions_summary = "Search, create, and edit email and SMS campaigns"
