on: [push, pull_request]

name: CI

jobs:
  CI:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.19.0, 22, 24]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js and pnpm
        uses: shop/setup-javascript-action@main
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript type checking
        run: |
          pnpm dlx --package=typescript tsc -p extensions/app-home --noEmit
          pnpm dlx --package=typescript tsc -p extensions/app-tools --noEmit
